#! /bin/sh

# License: GPL-v3
# Author: Steven Lee
# Email: shuangjianlee123@protonmail.com

PROG="bstyle"

USAGE="${PROG} -v | -l | -h | -t TARGET -s STYLE"

VERSION='0.2.0'

SUPPORTED_STYLES="qt|qt-c++ -> Qt (C++); linux -> Linux Kernel (C); google-c++ -> Google C++ (C++)"

TARGET=""

while getopts "vlht:s:" OPT;
do
  case $OPT in
    v)
      echo "${VERSION}"
      exit
      ;;
    h)
      echo "${USAGE}"
      exit
      ;;
    l)
      echo "${SUPPORTED_STYLES}"
      exit
      ;;
    t)
      TARGET="$TARGET $OPTARG"
      ;;
    s)
      STYLE="$OPTARG"
      ;;
    *)
      echo "Invalid Flags"
      echo "${USAGE}"
      exit
      ;; 
  esac

done

# Style:

QT_STYLE="\
--align-pointer=name \
--align-reference=name \
--attach-closing-while \
--attach-namespaces \
--attach-return-type-decl \
--break-blocks \
--convert-tabs \
--indent=spaces=4 \
--max-code-length=100 \
--max-instatement-indent=120 \
--pad-header \
--pad-oper \
--style=kr"

LINUX_STYLE="\
--align-pointer=name \
--attach-return-type-decl \
--break-after-logical \
--indent=force-tab=8 \
--max-code-length=90 \
--pad-header \
--pad-oper \
--style=linux \
--unpad-paren"

GOOGLE_STYLE="\
--align-pointer=type \
--align-reference=type \
--attach-classes \
--attach-closing-while \
--attach-extern-c \
--attach-namespaces \
--attach-return-type-decl \
--break-after-logical \
--break-blocks \
--convert-tabs \
--indent=spaces=2 \
--max-code-length=80 \
--pad-comma \
--pad-header \
--pad-oper \
--style=google"


ADDITIONAL_OPTIONS=""

case $STYLE in
  qt)
    ADDITIONAL_OPTIONS=$QT_STYLE
    ;;
  linux)
    ADDITIONAL_OPTIONS=$LINUX_STYLE
    ;;
  google|google-c++)
    ADDITIONAL_OPTIONS=$GOOGLE_STYLE
    ;;
  *)
    exit
    ;;
esac

_full_command="astyle -n ${ADDITIONAL_OPTIONS} ${TARGET}"

${_full_command}

exit


