#! /bin/sh

# License: GPL-v3
# Author: Steven Lee
# Email: shuangjianlee123@protonmail.com

PROG="bstyle"

USAGE="${PROG} -l | -h | -t TARGET -s STYLE"


SUPPORTED_STYLES="nice|nice-c -> Nice C (C); nice-c++ -> Nice C++ (C++); qt|qt-c++ -> Qt (C++); linux -> Linux Kernel (C); google|google-c++ -> Google C++ (C++)"

TARGET=""

while getopts "lht:s:" OPT;
do
  case $OPT in
    h)
      echo "${USAGE}"
      exit
      ;;
    l)
      echo "${SUPPORTED_STYLES}"
      exit
      ;;
    t)
      TARGET="$TARGET $OPTARG"
      ;;
    s)
      STYLE="$OPTARG"
      ;;
    *)
      echo "Invalid Flags"
      echo "${USAGE}"
      exit
      ;; 
  esac

done

# Style:

NICE_C_STYLE="\
--align-pointer=name \
--align-reference=name \
--attach-return-type-decl \
--break-blocks \
--convert-tabs \
--indent=spaces=4 \
--max-code-length=80 \
--max-instatement-indent=120 \
--pad-header \
--pad-oper \
--style=allman"

NICE_CXX_STYLE=$NICE_C_STYLE

QT_STYLE="\
--align-pointer=name \
--align-reference=name \
--attach-return-type-decl \
--break-blocks \
--convert-tabs \
--indent=spaces=4 \
--max-code-length=100 \
--max-instatement-indent=120 \
--pad-header \
--pad-oper \
--style=kr"

LINUX_STYLE="\
--align-pointer=name \
--attach-return-type-decl \
--break-after-logical \
--indent=force-tab=8 \
--max-code-length=90 \
--pad-header \
--pad-oper \
--style=linux \
--unpad-paren"

GOOGLE_CXX_STYLE="\
--align-pointer=type \
--align-reference=type \
--attach-return-type-decl \
--break-after-logical \
--break-blocks \
--convert-tabs \
--indent=spaces=2 \
--max-code-length=80 \
--pad-comma \
--pad-header \
--pad-oper \
--style=google"


GOOGLE_JAVA_STYLE="\
--attach-return-type-decl \
--break-blocks \
--convert-tabs \
--indent=spaces=2 \
--max-code-length=100 \
--mode=java \
--pad-comma \
--pad-header \
--pad-oper \
--style=java \
--unpad-paren"


ADDITIONAL_OPTIONS=""

case $STYLE in
  nice|nice-c)
    ADDITIONAL_OPTIONS=$NICE_C_STYLE
    ;;
  nice-c++)
    ADDITIONAL_OPTIONS=$NICE_CXX_STYLE
    ;;
  qt|qt-c++)
    ADDITIONAL_OPTIONS=$QT_STYLE
    ;;
  linux)
    ADDITIONAL_OPTIONS=$LINUX_STYLE
    ;;
  google|google-c++)
    ADDITIONAL_OPTIONS=$GOOGLE_CXX_STYLE
    ;;
  google-java)
    ADDITIONAL_OPTIONS=$GOOGLE_JAVA_STYLE
    ;;
  *)
    exit
    ;;
esac

_full_command="astyle -n ${ADDITIONAL_OPTIONS} ${TARGET}"

${_full_command}

exit


